dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.3
compiler:
  solc:
    version: 0.8.21
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.3"
dotenv: .env
wallets:
  from_key_1: ${PRIVATE_KEY_1}
  from_key_2: ${PRIVATE_KEY_2}
  # from_key: ${PRIVATE_KEY}
rpcs:
  infura_mainnet: ${WEB3_INFURA_PROJECT_ID}
networks:
  development:
    verify: False
  arbitrum-main-fork:
    verify: False
    dex_router_address: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506" # ARBITRUM Sushi
    dex_factory_address: "0xc35DADB65012eC5796536bD9864eD8773aBc74C4" # ARBITRUM Sushi
    dex_main_token_address: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1" # WETH
    deposit_token_address: "0xff970a61a04b1ca14834a43f5de4533ebddb5cc8" #USDC.e
    buy_token_addresses: [
        "0x912ce59144191c1204e64559fe8253a0e49e6548",
        "0x82af49447d8a07e3bd95bd0d56f35241523fbab1",
      ] # ARB + WETH
    vault_name: "ARB/WETH DCA Vault"
    vault_symbol: "ARB/WETH_DCA"
    vaults_factory_address: "0xB1fc77C3C581075c658B40691c02F61B7E429972"
    controller_address: "0xf4AfD9A546cFf7DDfA80FD340C20830ab46c5900"
    worker_address: "0x0d10dBD15D7F811d090B39E743bb523D79438199"
  arbitrum-main:
    verify: True
    dex_router_address: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506" # ARBITRUM Sushi
    dex_factory_address: "0xc35DADB65012eC5796536bD9864eD8773aBc74C4" # ARBITRUM Sushi
    dex_main_token_address: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1" # WETH
    deposit_token_address: "0xff970a61a04b1ca14834a43f5de4533ebddb5cc8" #USDC.e
    buy_token_addresses: [
        "0x912ce59144191c1204e64559fe8253a0e49e6548",
        "0x82af49447d8a07e3bd95bd0d56f35241523fbab1",
      ] # ARB + WETH
    vault_name: "ARB/WETH DCA Vault"
    vault_symbol: "ARB/WETH_DCA"
    vaults_factory_address: "0xB1fc77C3C581075c658B40691c02F61B7E429972"
    controller_address: "0xf4AfD9A546cFf7DDfA80FD340C20830ab46c5900"
    worker_address: "0x0d10dBD15D7F811d090B39E743bb523D79438199"
strategy-params:
  buy_amounts: [10_000, 10_000] # Considering deposit token addr
  buy_frequency: 0 # Daily
  strategy_type: 0 # DCA
protocol-params:
  treasury_fixed_fee_on_vault_creation: 100_000_000_000_000 # Ether amount (0.001)
  creator_percentage_fee_on_deposit: 25 #0.25%
  treasury_percentage_fee_on_balance_update: 25 #0.25%
