dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.3
compiler:
  solc:
    version: 0.8.21
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.3"
dotenv: .env
wallets:
  from_key_1: ${PRIVATE_KEY_1}
  from_key_2: ${PRIVATE_KEY_2}
  # from_key: ${PRIVATE_KEY}
