dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.3
compiler:
  solc:
    version: 0.8.21
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.3"
dotenv: .env
wallets:
  from_key_1: ${PRIVATE_KEY_1}
  from_key_2: ${PRIVATE_KEY_2}
  # from_key: ${PRIVATE_KEY}
networks:
  development:
    verify: False
  arbitrum-main-fork:
    verify: False
    dex_router_address: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506" # ARBITRUM Sushi
    dex_factory_address: "0xc35DADB65012eC5796536bD9864eD8773aBc74C4" # ARBITRUM Sushi
    dex_main_token_address: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1" # WETH
    vaults_factory_address: "0xbCD518ee07eE168aDbF6A1d773b21bD2e11392c9"
    controller_address: "0x1e4cdDadE599e963E09AF9CFE0cea218D392b1A3"
    worker_address: "0xB2CeE323903Fc416290b2D4eF35Bd9E88efd5df4"
  arbitrum-main:
    verify: True
    dex_router_address: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506" # ARBITRUM Sushi
    dex_factory_address: "0xc35DADB65012eC5796536bD9864eD8773aBc74C4" # ARBITRUM Sushi
    dex_main_token_address: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1" # WETH
    vaults_factory_address: "0xbCD518ee07eE168aDbF6A1d773b21bD2e11392c9"
    controller_address: "0x1e4cdDadE599e963E09AF9CFE0cea218D392b1A3"
    worker_address: "0xB2CeE323903Fc416290b2D4eF35Bd9E88efd5df4"
