dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.3
compiler:
  solc:
    version: 0.8.21
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.3"
dotenv: .env
wallets:
  from_key_1: ${PRIVATE_KEY_1}
  from_key_2: ${PRIVATE_KEY_2}
  # from_key: ${PRIVATE_KEY}
networks:
  development:
    verify: False
  arbitrum-main-fork:
    verify: False
    dex_router_address: "0xbee5c10cf6e4f68f831e11c1d9e59b43560b3642" # ARBITRUM Trader Joe
    vaults_factory_address: "0x5d2ffdb504ea97c191deeeda364832b1cc72246f"
    controller_address: "0x3058ff7580913561fED8b14CC0C464Be7e75A6B3"
    worker_address: "0xC54372F61bC0a3D8f8E89D1F532fa0ee3b92bF3f"
  arbitrum-main:
    verify: True
    dex_router_address: "0xbee5c10cf6e4f68f831e11c1d9e59b43560b3642" # ARBITRUM Trader Joe
    vaults_factory_address: "0x5d2ffdb504ea97c191deeeda364832b1cc72246f"
    controller_address: "0x3058ff7580913561fED8b14CC0C464Be7e75A6B3"
    worker_address: "0xC54372F61bC0a3D8f8E89D1F532fa0ee3b92bF3f"
