dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.3
compiler:
  solc:
    version: 0.8.21
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.3"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}